# -*- coding: utf-8 -*-
"""A-DM-V01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PThLaMnE8oe7R9rMRb8iAwhnHZPRsrk2
"""

from google.colab import drive
drive.mount('/gdrive')

cd /gdrive/My\ Drive/notebooks/Arghavan

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../../dataset/exp1testing.csv")

#df=df.drop(columns=['trial'])

#df.head()

df['length'] = df['length'].map({'Long': 1, 'Short': 0})
df['delay'] = df['delay'].map({'Immed': 1, 'Delay': 0})
#df['length'][df['length'] == 'Long']=1
#df['length'][df['length'] == 'Short']=0

df.tail()

df.describe()

correlation=df.corr(method ='pearson')

plt.matshow(df.corr())
plt.show()

df0=df.loc[df['subj']==0]
#df1=df0.loc[(df0['length']==0) & (df0['delay']==1)]
#df1.shape

for i in range(107):
    exec("df%d=df.loc[df['subj']==%d]"%(i,i))

#df2

df2=df0.loc[(df0['length']==1) & (df0['delay']==1)]
df2.shape

df3=df0.loc[(df0['length']==1) & (df0['delay']==0)]
df3.shape

df4=df0.loc[(df0['length']==0) & (df0['delay']==1)]
df4.shape

"""# HF & LF"""

dfHF=df.loc[df['wf']=='HF']
dfLF=df.loc[df['wf']=='LF']

HFcmean=dfHF['correct'].mean()
LFcmean=dfLF['correct'].mean()

HFcmean

LFcmean

HFdmean=dfHF['delay'].mean()
LFdmean=dfLF['delay'].mean()

HFdmean

LFdmean

"""# Long & short"""

dfll=df.loc[df['length']==1]
dflsh=df.loc[df['length']==0]

llcmean=dfll['correct'].mean()
lshcmean=dflsh['correct'].mean()

llcmean

lshcmean

"""#Long&Immediate"""

dfLI=df.loc[(df['length']==1) & (df['delay']==1)]

dfLI_list = []
for i in range(107):
    exec("dfLI%d=dfLI.loc[dfLI['subj']==%d]"%(i,i))
    exec("dfLI_list.append(dfLI%d)"%(i))

Xs = []
Ys = []
for dfLI_element in dfLI_list:
    Ys.append(dfLI_element['RT'].values)
    Xs.append(dfLI_element['trial'].values)

np.array(Ys).shape

Y_avg = np.sum(Ys,axis=0)/107



plt.plot(Xs[0][2:],Y_avg[2:])

#y=df0LI['RT']
#x=df0LI['trial']

#plt.plot(x,y)

"""#HF"""

dfHF_list = []
for i in range(107):
    exec("dfHF%d=dfLI.loc[dfHF['subj']==%d]"%(i,i))
    exec("dfHF_list.append(dfHF%d)"%(i))

Xs = []
Ys = []
for dfLI_element in dfLI_list:
    Ys.append(dfLI_element['RT'].values)
    Xs.append(dfLI_element['trial'].values)

np.array(Ys).shape

"""# subject=0&Long&Immediate"""

#suject=0&Long&Immediate
df0=df.loc[df['subj']==0]
df0LI=df0.loc[(df0['length']==1) & (df0['delay']==1)]

df0LI;

df0LI[['RT','trial']].corr()

df

df0LLI=df0LI.loc[(df0LI['type']=='lure')]
df0HLLI=df0LI.loc[(df0LI['wf']=='HF')]
df0LLI[['RT','trial']].corr()
#df0HLLI

df0[['RT','trial']].corr()

y=df0LI['RT']
x=df0LI['trial']

plt.plot(x,y)

#z=df0LI

"""# Long & and Immediate for all subjects"""

dfLI=df.loc[(df['length']==1) & (df['delay']==1)]
#dfbase=dfLI.loc[dfLI['subj']==0]
dfgLI=dfLI.groupby(['subj'])
dfgLI.keys

dfLI.groupby(['subj'],['trial']).count()['RT'].unstack().plot(ax=ax)

dftest=[]
for i in  range (107):
    dftest.append(dfLI.loc[dfLI['subj']=='i'])
    #dftest=df.loc[(df['length']==1) & (df['delay']==1)]

dftest

dfLI

"""# Start"""

df[['RT','trial']].corr()

dfcorr=df.loc[df['correct']==1]
dffal=df.loc[df['correct']==0]

dfcorr['RT'].mean()
dfcorr['RT'].std()

dffal['RT'].mean()
dffal['RT'].std()

#df.plot(kind='scatter',x='num_children',y='num_pets',color='red')
#plt.show()
#dfcorr.plot(x='col_name_1', y='col_name_2', style='o')

plt.plot(dfcorr['RT'])

df.shape

plt.hist(dffal['RT'])

x=[]
for i in range(1,107):
    
    s=df[df['subj'] == i]['RT'].mean()
    x.append(s)
y=[]
for i in range(1,107):
    
    s1=dfcorr[dfcorr['subj'] == i]['RT'].mean()
    y.append(s1)
z=[]
for i in range(1,107):
    
    s2=dffal[dffal['subj'] == i]['RT'].mean()
    y.append(s2)

plt.plot(x)



df.loc[df['subj']==0].loc[df['block']=='b0']

